### ISSUE TITLE
Update an already deployed Jar

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/gradle-javaee-plugin#2]
Hello,

Is there any way to deploy an update to an already deployed Jar ? I can't see the Gradle task for that.

Thank you!

**Comment by sink772** [comment]
It's now supported in v0.7.9 release.
https://search.maven.org/artifact/foundation.icon/gradle-javaee-plugin/0.7.9/jar
https://github.com/icon-project/gradle-javaee-plugin#deployment-for-update

**Comment by ICONationDevTeam** [comment]
Awesome, thanks!
