### ISSUE TITLE
Optimized Jar doesn't detect give java/util/Objects as non allowed method

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/gradle-javaee-plugin#4]
While optimizing the jar, it should detect java.util.Objects as non allowed method but it doesn't detect. Which is only found later while deploying the contracts.

**Comment by ajaya-man** [comment]
Some further undetected libraries are java.util.HashMap, java.util.ArrayList.

**Comment by sink772** [comment]
@ajaya-man 
This issue has been resolved in https://github.com/icon-project/gradle-javaee-plugin/releases/tag/v0.8.1
Please test with the updated version and let me know if it works for you.
