### ISSUE TITLE
@Eventlog annotation outside of main class is not working

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/gradle-javaee-plugin#5]
Eventlogs created in classes other than the main one does not work during runtime, however complies and deploys without any issue.
Usage of Context.logEvent works as expected. So not entirely sure where the problem arises.

**Comment by sink772** [comment]
Currently, only classes that can be reached from the Main class through inheritance relationships can have the '@EventLog' annotation.  This is the design spec, nothing else.
Personally, I don't see the need to support it for other utility classes not related to inheritance relationships with the Main class.
